apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: spring
spec:
  selector:
    matchLabels:
      app: spring
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring
        image: mavenimage:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: 1536Mi
          requests:
            cpu: "1"
            memory: 1536Mi
        envFrom:
        - configMapRef:
            name: spring-config
