apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
spec:
  selector:
    matchLabels:
      app: spring
  replicas: 2
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring
        image: Sample_java_docker_image:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: 1024Mi
          requests:
            cpu: "1"
            memory: 1024Mi
        envFrom:
        - configMapRef:
            name: spring-config
